CREATE DATABASE if NOT EXISTS PROJETOCHAMAKI;

Use PROJETOCHAMAKI;


CREATE TABLE USUARIO(
    ID Varchar (55),
    NOME Varchar (55),
    TELEFONE Varchar (20),
    SENHA Varchar (55),
    PRIMARY KEY (ID)
    );

CREATE TABLE VOLUNTARIO(
    ID Varchar (55),
    NOME Varchar (55),
    CPF Varchar (20),
    NASCIMENTO DATETIME (6),
    EMAIL Varchar (55),
    SENHA Varchar (55),
    TELEFONE Varchar (55),
    CIDADE Varchar (55),
    ENDERECO Varchar (55),
    BAIRRO Varchar (30),
    NUMERO_CASA Varchar (5),    
    PRIMARY KEY (ID)
    );


CREATE TABLE CHAMADOS(
    ID Varchar (55),
    IDUSUARIO Varchar (55),
    IDVOLUNTARIO Varchar (55),
    TELEFONE Varchar (55),
    DESCRICAO Varchar (255),
    TIPO Integer (155),
    PRIMARY KEY (ID)
    );

ALTER TABLE CHAMADOS ADD FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID);

ALTER TABLE chamados ADD COLUMN IDVOLUNTARIO VARCHAR (255);

ALTER TABLE CHAMADOS ADD FOREIGN KEY (IDVOLUNTARIO) REFERENCES VOLUNTARIO(ID);

ALTER TABLE chamados ADD COLUMN VOLUNTARIOID VARCHAR (255);
